# Configuration for Neovide

# mkdir -p ~/.config/neovide
# ln -s ~/.config/nvim/config.toml ~/.config/neovide/config.toml

# --- Window frame ---
frame = "none"

# --- Fonts ---
[font]
size = 13
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "Elephant"
style = "Medium"

[[font.bold]]
family = "Elephant"
style = "ExtraBold"

# fallback font
[[font.normal]]
family = "Vazir Code Hack"
