# Configuration for Neovide

# mkdir -p ~/.config/neovide
# ln -s ~/.config/nvim/config.toml ~/.config/neovide/config.toml

# --- Window frame ---
frame = "none"

# --- Fonts ---
[font]
size = 13
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "CommitMono"

[[font.bold]]
family = "CommitMono"

# fallback font
[[font.normal]]
family = "Vazir Code Hack"
style = "Normal"

[font.features]
"Geist Mono" = ["+ss02", "+ss03", "+ss06", "+ss09", "+ss11"]
